version: "3.9"

services:
  web:
    build: .
    container_name: creatiself_web
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: creatiself_nginx
    ports:
      - "8080:80"
    volumes:
      - static_volume:/app/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  static_volume:  # ✅ Esta línea faltaba, define el volumen nombrado
