# Generated by Django 4.2.20 on 2025-05-23 23:24

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('password', models.CharField(default='123456', max_length=128)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuario_set', related_query_name='usuario', to='auth.group')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('modalidad', models.CharField(choices=[('virtual', 'Virtual'), ('presencial', 'Presencial')], max_length=50)),
                ('motivo_consulta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='Sin descripción', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_paciente', models.CharField(choices=[('individual', 'Individual'), ('infantil', 'Infantil')], max_length=10)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('nombre2', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
                ('direccion', models.TextField()),
                ('nivel_academico', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('bachillerato', 'Bachillerato'), ('tecnico', 'Técnico'), ('tecnologo', 'Tecnólogo'), ('pregrado', 'Pregrado'), ('licenciatura', 'Licenciatura'), ('especializacion', 'Especialización'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado'), ('postdoctorado', 'Postdoctorado'), ('diplomado', 'Diplomado'), ('curso', 'Curso'), ('sin_estudios', 'Sin estudios formales')], default='sin_estudios', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('antecedentes_personales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.antecedentespersonales')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ciudad')),
                ('condicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.condicion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
                ('parentesco', models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('abuelo', 'Abuelo'), ('abuela', 'Abuela'), ('bisabuelo', 'Bisabuelo'), ('bisabuela', 'Bisabuela'), ('hermano', 'Hermano'), ('hermana', 'Hermana'), ('tio', 'Tío'), ('tia', 'Tía'), ('primo', 'Primo'), ('prima', 'Prima'), ('padrino', 'Padrino'), ('madrina', 'Madrina'), ('sin_parentesco', 'Sin parentesco')], default='sin_parentesco', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(choices=[('pareja', 'Pareja'), ('familiar', 'Familiar'), ('otro', 'Otro')], max_length=50)),
                ('fecha_relacion', models.DateField(auto_now_add=True)),
                ('paciente1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_como_paciente1', to='app.paciente')),
                ('paciente2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_como_paciente2', to='app.paciente')),
            ],
            options={
                'unique_together': {('paciente1', 'paciente2')},
            },
        ),
        migrations.CreateModel(
            name='PacienteRepresentante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.representante')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais'),
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais'),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('nombre2', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
                ('nivel_academico', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('bachillerato', 'Bachillerato'), ('tecnico', 'Técnico'), ('tecnologo', 'Tecnólogo'), ('pregrado', 'Pregrado'), ('licenciatura', 'Licenciatura'), ('especializacion', 'Especialización'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado'), ('postdoctorado', 'Postdoctorado'), ('diplomado', 'Diplomado'), ('curso', 'Curso'), ('sin_estudios', 'Sin estudios formales')], default='sin_estudios', max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ciudad')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('anotacion', models.TextField()),
                ('conclusion', models.TextField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cita')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='pareja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.relacionpaciente'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_set', related_query_name='usuario', to='auth.permission'),
        ),
    ]
