# Generated by Django 4.2.20 on 2025-06-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cita_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
