# Generated by Django 4.2.20 on 2025-05-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_empleado_actualizado_en_empleado_creado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tipo_paciente',
            field=models.CharField(choices=[('individual', 'Individual'), ('infantil', 'Infantil')], max_length=10),
        ),
    ]
