# Generated by Django 4.2.20 on 2025-06-19 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_condicion_descripcion_alter_usuario_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='pareja',
            new_name='relacion',
        ),
    ]
