# Generated by Django 4.2.20 on 2025-03-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='parentesco',
            field=models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('abuelo', 'Abuelo'), ('abuela', 'Abuela'), ('bisabuelo', 'Bisabuelo'), ('bisabuela', 'Bisabuela'), ('hermano', 'Hermano'), ('hermana', 'Hermana'), ('tio', 'Tío'), ('tia', 'Tía'), ('primo', 'Primo'), ('prima', 'Prima'), ('padrino', 'Padrino'), ('madrina', 'Madrina'), ('sin_parentesco', 'Sin parentesco')], default='sin_parentesco', max_length=20),
        ),
        migrations.DeleteModel(
            name='Parentesco',
        ),
    ]
