# Generated by Django 4.2.20 on 2025-06-19 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_pareja_cita_relacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='relacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.relacionpaciente', verbose_name='Relación/Pareja'),
        ),
    ]
