# Generated by Django 4.2.20 on 2025-04-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_representante_parentesco_delete_parentesco'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(choices=[('pareja', 'Pareja'), ('familiar', 'Familiar'), ('otro', 'Otro')], max_length=50)),
                ('fecha_relacion', models.DateField(auto_now_add=True)),
                ('paciente1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_como_paciente1', to='app.paciente')),
                ('paciente2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_como_paciente2', to='app.paciente')),
            ],
            options={
                'unique_together': {('paciente1', 'paciente2')},
            },
        ),
    ]
