# Generated by Django 4.2.20 on 2025-07-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cita_relacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empleado', verbose_name='Profesional Asignado'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='historial',
            field=models.TextField(blank=True, help_text='Registro detallado del historial psicológico del paciente', null=True, verbose_name='Historial Psicológico'),
        ),
    ]
